### ISSUE TITLE
Screen Shake Effects

### ISSUE THREAD

**Issue by tomkaar** [tomkaar/CanvasAtariTest#4]
Shake screen
- Ball hits Brick/ Block
- Ball hits item
- Ball hits Pad
- Every time you lose a life

**Comment by Leolainen** [comment]
Vill föreslå att om man blir av med ett liv får det gärna bli en röd ton över skärmen medan det skakar.

**Comment by tomkaar** [comment]
oo ja jag gillar den ideen
