### ISSUE TITLE
Life

### ISSUE THREAD

**Issue by tomkaar** [tomkaar/CanvasAtariTest#8]
Game over when life is 0 or less

**Comment by Leolainen** [comment]
Kan fixa denna i samma veva som hold ball grejen

**Comment by tomkaar** [comment]
Jag har en klar kod som jag kan lägga till annars, där man har ett total antal liv och funktioner där man kan lägga till och ta bort liv från totalen

**Comment by Leolainen** [comment]
Oke. Lägg till det så syr jag ihop det med hold ball

**Comment by tomkaar** [comment]
Fixar det när jag kommer till en dator

**Comment by tomkaar** [comment]
Pushed
